### ISSUE TITLE
can not launch program

### ISSUE THREAD

**Issue by ozohhub** [ergrelet/themida-unmutate#2]
Traceback (most recent call last):
  File "themida_unmutate\__main__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "themida_unmutate\main.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "themida_unmutate\logging.py", line 3, in <module>
ModuleNotFoundError: No module named 'lief'
[35268] Failed to execute script '__main__' due to unhandled exception!

**Comment by ergrelet** [comment]
Hi!
This happens when using the x64 executable from the release artifacts, is that correct?

**Comment by ergrelet** [comment]
This is fixed with release 0.1.1.
